### ISSUE TITLE
Dependency problems [bug?]

### ISSUE THREAD

**Issue by yjftsjthsd-g** [sgnn7/ez_gpg#3]
I'm trying to install/run this, so I tried pip-installing in a virtualenv, then when that didn't work I tried downloading the repo and running setup.py in a virtualenv, but both ways gave me this error:

```
$ ./ezgpg
Traceback (most recent call last):
  File "./ezgpg", line 5, in <module>
    from ez_gpg.ui import EzGpg
  File "/home/me/workspace/ez_gpg-master/ez_gpg/ui.py", line 3, in <module>
    import gi
ImportError: No module named 'gi'
```

So, I tried `pip3 install gi`, which gets me... further?

```
$ ezgpg
Traceback (most recent call last):
  File "/home/me/myvirtualenv/bin/ezgpg", line 7, in <module>
    from ez_gpg.ui import EzGpg
  File "/home/me/myvirtualenv/lib/python3.5/site-packages/ez_gpg/ui.py", line 3, in <module>
    import gi
  File "/home/me/myvirtualenv/lib/python3.5/site-packages/gi/__init__.py", line 39
    print url
            ^
```

So now I'm out of ideas and request help. Are you using a different dependency for `gi`? I also pip-installed `python-gnutls` in the virtualenv. I've tried this on Arch Linux and OpenBSD with identical results.

**Comment by sgnn7** [comment]
@yjftsjthsd-g The `gi` is Python's bindings for gobject introspection and `pip3` (vs `pip`) is mandatory since the codebase is targeting python3 so that should in theory have worked. 

It also doesn't seem like you included the error output for that second stacktrace but what's really interesting with it is that the offending line is `print url` which is not valid in python3 but only in python2 (python3 mandates parens around prints and it would be `print(url)`) so my best guess is that maybe virtualenv is working with python2's version of gobject `gi` package even though the path says `python3.5`.

After some googling, it might seem like `virtualenv` isn't the best vs `venv` to use for python3 but [this](https://superuser.com/questions/1039369/how-to-create-a-python3-virtual-environment-as-of-2016) thread says that you might be able to get it going with the following:

```
$ sudo apt-get install python-virtualenv
$ virtualenv -p python3 env
$ source ./env/bin/activate
```

**Comment by yjftsjthsd-g** [comment]
It appears that running a Python 3 virtualenv still produces the same issue. I'm starting wonder whether this is a bug in gi.

```
[me@dratini ez_gpg]$ virtualenv -p python3 env
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/me/ez_gpg/env/bin/python3
Also creating executable in /home/me/ez_gpg/env/bin/python
Installing setuptools, pip, wheel...done.
[me@dratini ez_gpg]$ source ./env/bin/activate
(env) [me@dratini ez_gpg]$ pip3 install gi
Collecting gi
  Downloading gi-1.2.tar.gz
Collecting requests (from gi)
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 1.2MB/s 
Building wheels for collected packages: gi
  Running setup.py bdist_wheel for gi ... done
  Stored in directory: /home/me/.cache/pip/wheels/1f/25/57/1206beb53137524ad7ae8cbe74e246a56dc4e213dc8a91a6e2
Successfully built gi
Installing collected packages: requests, gi
Successfully installed gi-1.2 requests-2.10.0
(env) [me@dratini ez_gpg]$ ./setup.py install
running install
running bdist_egg
running egg_info
creating ezgpg.egg-info
writing requirements to ezgpg.egg-info/requires.txt
writing ezgpg.egg-info/PKG-INFO
writing dependency_links to ezgpg.egg-info/dependency_links.txt
writing entry points to ezgpg.egg-info/entry_points.txt
writing top-level names to ezgpg.egg-info/top_level.txt
writing manifest file 'ezgpg.egg-info/SOURCES.txt'
reading manifest file 'ezgpg.egg-info/SOURCES.txt'
writing manifest file 'ezgpg.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/ez_gpg
copying ez_gpg/__init__.py -> build/lib/ez_gpg
copying ez_gpg/ui.py -> build/lib/ez_gpg
copying ez_gpg/utils.py -> build/lib/ez_gpg
creating build/lib/ez_gpg/data
copying ez_gpg/data/__init_.py -> build/lib/ez_gpg/data
copying ez_gpg/data/__init__.py -> build/lib/ez_gpg/data
copying ez_gpg/data/decrypt_window.ui -> build/lib/ez_gpg/data
copying ez_gpg/data/encrypt_window.ui -> build/lib/ez_gpg/data
copying ez_gpg/data/key_management.ui -> build/lib/ez_gpg/data
copying ez_gpg/data/main_window.ui -> build/lib/ez_gpg/data
copying ez_gpg/data/sign_window.ui -> build/lib/ez_gpg/data
copying ez_gpg/data/verify_window.ui -> build/lib/ez_gpg/data
copying ez_gpg/data/application.css -> build/lib/ez_gpg/data
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/ez_gpg
copying build/lib/ez_gpg/__init__.py -> build/bdist.linux-x86_64/egg/ez_gpg
copying build/lib/ez_gpg/ui.py -> build/bdist.linux-x86_64/egg/ez_gpg
copying build/lib/ez_gpg/utils.py -> build/bdist.linux-x86_64/egg/ez_gpg
creating build/bdist.linux-x86_64/egg/ez_gpg/data
copying build/lib/ez_gpg/data/__init_.py -> build/bdist.linux-x86_64/egg/ez_gpg/data
copying build/lib/ez_gpg/data/__init__.py -> build/bdist.linux-x86_64/egg/ez_gpg/data
copying build/lib/ez_gpg/data/decrypt_window.ui -> build/bdist.linux-x86_64/egg/ez_gpg/data
copying build/lib/ez_gpg/data/encrypt_window.ui -> build/bdist.linux-x86_64/egg/ez_gpg/data
copying build/lib/ez_gpg/data/key_management.ui -> build/bdist.linux-x86_64/egg/ez_gpg/data
copying build/lib/ez_gpg/data/main_window.ui -> build/bdist.linux-x86_64/egg/ez_gpg/data
copying build/lib/ez_gpg/data/sign_window.ui -> build/bdist.linux-x86_64/egg/ez_gpg/data
copying build/lib/ez_gpg/data/verify_window.ui -> build/bdist.linux-x86_64/egg/ez_gpg/data
copying build/lib/ez_gpg/data/application.css -> build/bdist.linux-x86_64/egg/ez_gpg/data
byte-compiling build/bdist.linux-x86_64/egg/ez_gpg/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/ez_gpg/ui.py to ui.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/ez_gpg/utils.py to utils.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/ez_gpg/data/__init_.py to __init_.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/ez_gpg/data/__init__.py to __init__.cpython-34.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-3.4
copying and adjusting ezgpg -> build/scripts-3.4
changing mode of build/scripts-3.4/ezgpg from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.4/ezgpg -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/ezgpg to 755
copying ezgpg.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ezgpg.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ezgpg.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ezgpg.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ezgpg.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ezgpg.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ezgpg.egg-info/zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/ezgpg-0.2.0-py3.4.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ezgpg-0.2.0-py3.4.egg
Copying ezgpg-0.2.0-py3.4.egg to /home/me/ez_gpg/env/lib/python3.4/site-packages
Adding ezgpg 0.2.0 to easy-install.pth file
Installing ezgpg script to /home/me/ez_gpg/env/bin
Installing ezgpg script to /home/me/ez_gpg/env/bin

Installed /home/me/ez_gpg/env/lib/python3.4/site-packages/ezgpg-0.2.0-py3.4.egg
Processing dependencies for ezgpg==0.2.0
Searching for python-gnupg
Reading https://pypi.python.org/simple/python-gnupg/
Best match: python-gnupg 0.3.8
Downloading https://pypi.python.org/packages/29/ba/b12f3e97eed74573c03fb6dab9f87af2b56bd5626d51a2b4aad5ee106ece/python-gnupg-0.3.8.tar.gz#md5=54d312056cb8903358bdd0a18522f702
Processing python-gnupg-0.3.8.tar.gz
Writing /tmp/easy_install-wrdy62a0/python-gnupg-0.3.8/setup.cfg
Running python-gnupg-0.3.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-wrdy62a0/python-gnupg-0.3.8/egg-dist-tmp-l3i1lr5s
zip_safe flag not set; analyzing archive contents...
Moving python_gnupg-0.3.8-py3.4.egg to /home/me/ez_gpg/env/lib/python3.4/site-packages
Adding python-gnupg 0.3.8 to easy-install.pth file

Installed /home/me/ez_gpg/env/lib/python3.4/site-packages/python_gnupg-0.3.8-py3.4.egg
Finished processing dependencies for ezgpg==0.2.0
(env) [me@dratini ez_gpg]$ ezgpg 
Traceback (most recent call last):
  File "/home/me/ez_gpg/env/bin/ezgpg", line 9, in <module>
    load_entry_point('ezgpg==0.2.0', 'gui_scripts', 'ezgpg')()
  File "/home/me/ez_gpg/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/me/ez_gpg/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/me/ez_gpg/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/me/ez_gpg/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/home/me/ez_gpg/env/lib/python3.4/site-packages/ezgpg-0.2.0-py3.4.egg/ez_gpg/ui.py", line 3, in <module>
  File "/home/me/ez_gpg/env/lib/python3.4/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
(env) [me@dratini ez_gpg]$ pip3 install python-gnutls
Collecting python-gnutls
  Downloading python-gnutls-3.0.0.tar.gz (40kB)
    100% |████████████████████████████████| 40kB 655kB/s 
Building wheels for collected packages: python-gnutls
  Running setup.py bdist_wheel for python-gnutls ... done
  Stored in directory: /home/me/.cache/pip/wheels/79/d1/b9/9e120b9ea64226e0c4c317624ba22bc500e43b20e845a6ef61
Successfully built python-gnutls
Installing collected packages: python-gnutls
Successfully installed python-gnutls-3.0.0
(env) [me@dratini ez_gpg]$ ezgpg 
Traceback (most recent call last):
  File "/home/me/ez_gpg/env/bin/ezgpg", line 9, in <module>
    load_entry_point('ezgpg==0.2.0', 'gui_scripts', 'ezgpg')()
  File "/home/me/ez_gpg/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/me/ez_gpg/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/me/ez_gpg/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/me/ez_gpg/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/home/me/ez_gpg/env/lib/python3.4/site-packages/ezgpg-0.2.0-py3.4.egg/ez_gpg/ui.py", line 3, in <module>
  File "/home/me/ez_gpg/env/lib/python3.4/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by sgnn7** [comment]
Hmm... I'm going to see if I can figure out what's going on here this weekend

**Comment by yjftsjthsd-g** [comment]
Thanks:) Let me know if I can help. Are you able to reproduce the problem on your system in a virtualenv? I'm just doing:

```
$ virtualenv -p python3 env
$ source ./env/bin/activate
$ pip3 install gi 
$ pip3 install python-gnutls
$ ./setup.py install
$ ezgpg
```

**Comment by sgnn7** [comment]
@yjftsjthsd-g Ok - figured this one out (in a way). Python virtualenv doesn't expose `python-gi` to the container by default and it has to be built in that env or linked from the host package if you want this API on top of which `pip` package `gi` just doesn't work. For a bit more in-depth view around why this is the case, you can read up on it [here](https://stackoverflow.com/questions/12830662/python-package-installed-globally-but-not-in-a-virtualenv-pygtk) and [here](https://stackoverflow.com/questions/26678457/how-do-i-install-python3-gi-within-virtualenv/31687434).

As for a quick solution to this, you can easily make this work by doing the following:
- Remove all your virtualenv files in the repo (a clean checkout might be best for this)
- Install `python3-gi` system package
- Create virtualenv with `virtualenv  --system-site-packages -p python3 <dir>`
- `source <dir>/bin/activate`
- Install prerequisites if host doesn't have them (i.e. `python3-gnupg`)
- `./ezgpg`

**Comment by sgnn7** [comment]
@yjftsjthsd-g Did my last comment make things work? If so, I'll close the issue.

**Comment by yjftsjthsd-g** [comment]
Sorry, haven't had a chance to test properly. My main system doesn't appear to have a python3-gi package in the repos, so I'll try on a different system soon.

**Comment by jedie** [comment]
I'm little confused... What is really this "**gi**" lib?!?

It's not https://pypi.python.org/pypi/gi or?
So **pip3 install gi** selects just the wrong package, isn't it?

It's the dist packge **python3-gi**...
From https://wiki.gnome.org/Projects/PyGObject:

> Fedora Packages: pygobject3, python3-gobject
> Debian Packages: python-gi and python3-gi
> Ubuntu Packages: python-gi and python3-gi

There is also a link to the git repro and the setup.py contains the package name **pygobject**: https://git.gnome.org/browse/pygobject/tree/setup.py

Conclusion: You must use **pip install pygobject** isn't it?

**Comment by jedie** [comment]
Hm. No, **pygobject** is not the right PyPi package, because it's only for Python 2 :(

So, it's not possible to install **gi** via PyPi, isn't it?

**Comment by sgnn7** [comment]
@jedie Yes, that is correct (as far as I know) since these are system binaries and not just some python code library.

**Comment by sgnn7** [comment]
This in theory should be fixed now with the latest changes in #6 . Feel free to reopen if needed!
